# Generated by Django 5.0.3 on 2024-04-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0006_course_degree_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Degree_program',
            new_name='DegreeProgram',
        ),
        migrations.AddField(
            model_name='course',
            name='year_taught',
            field=models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')], default=1),
            preserve_default=False,
        ),
    ]
