# Generated by Django 5.0.3 on 2024-04-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0008_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
