# Generated by Django 5.0.3 on 2024-04-12 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0011_rename_user_id_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
