# Generated by Django 5.0.3 on 2024-04-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0013_course_notes_course_semester_delete_lecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='degree_id',
        ),
        migrations.AddField(
            model_name='course',
            name='degree_id',
            field=models.ManyToManyField(to='learning_system.degreeprogram'),
        ),
    ]
