# Generated by Django 5.0.3 on 2024-04-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0014_remove_course_degree_id_course_degree_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year_taught',
            field=models.CharField(),
        ),
    ]
