# Generated by Django 5.0.3 on 2024-04-24 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0015_alter_course_year_taught'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='year_taught',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_system.year'),
        ),
    ]
