# Generated by Django 5.0.3 on 2024-04-24 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0016_year_alter_course_year_taught'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='year_taught',
        ),
    ]
