# Generated by Django 5.0.3 on 2024-04-30 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0022_remove_course_semester_remove_course_year_taught_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearcoursesemester',
            name='degree',
            field=models.ForeignKey(default='CS', on_delete=django.db.models.deletion.CASCADE, to='learning_system.degreeprogram'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yearcoursesemester',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_id', to='learning_system.course'),
        ),
    ]
