# Generated by Django 5.0.3 on 2024-04-30 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0023_yearcoursesemester_degree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='degree_id',
        ),
    ]
