# Generated by Django 5.0.3 on 2024-04-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0024_remove_course_degree_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='yearcoursesemester',
            field=models.ManyToManyField(related_name='yearcourse', to='learning_system.yearcoursesemester'),
        ),
    ]
