# Generated by Django 5.0.3 on 2024-04-30 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0025_course_yearcoursesemester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='yearcoursesemester',
        ),
        migrations.AddField(
            model_name='course',
            name='degree_id',
            field=models.ForeignKey(default='CS', on_delete=django.db.models.deletion.CASCADE, to='learning_system.degreeprogram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(choices=[(1, 'first'), (2, 'second')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(choices=[(1, 'first'), (2, 'second'), (3, 'third'), (4, 'fourth')], default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='YearCourseSemester',
        ),
    ]
