# Generated by Django 5.0.3 on 2024-04-30 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0026_remove_course_yearcoursesemester_course_degree_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='degree_id',
            new_name='degree',
        ),
    ]
