# Generated by Django 5.0.3 on 2024-04-30 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0027_rename_degree_id_course_degree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pastpaper',
            old_name='course_id',
            new_name='course',
        ),
    ]
