# Generated by Django 5.0.3 on 2024-04-12 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0010_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
