# Generated by Django 5.0.3 on 2024-04-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0012_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='notes',
            field=models.TextField(default='sokaa', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(choices=[(1, 'first'), (2, 'second')], default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
    ]
