# Generated by Django 5.0.3 on 2024-04-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0018_course_year_taught'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='year_taught',
        ),
        migrations.AddField(
            model_name='course',
            name='year_taught',
            field=models.ManyToManyField(to='learning_system.year'),
        ),
    ]
