# Generated by Django 5.0.3 on 2024-04-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0019_remove_course_year_taught_course_year_taught'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
