# Generated by Django 5.0.3 on 2024-04-30 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0021_remove_course_semester_course_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='course',
            name='year_taught',
        ),
        migrations.CreateModel(
            name='YearCourseSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1, 'first'), (2, 'second'), (3, 'third'), (4, 'foruth')])),
                ('semester', models.IntegerField(choices=[(1, 'first'), (2, 'second')])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='learning_system.course')),
            ],
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
