# Generated by Django 5.0.3 on 2024-05-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0029_course_is_free_delete_tutorial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_free',
        ),
        migrations.AddField(
            model_name='pastpaper',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
