# Generated by Django 5.0.6 on 2024-05-11 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0030_remove_course_is_free_pastpaper_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpaper',
            name='solution',
            field=models.FileField(blank=True, null=True, upload_to='solutions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png'])]),
        ),
    ]
