# Generated by Django 5.0.6 on 2024-05-15 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0031_alter_pastpaper_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpaper',
            name='file',
            field=models.FileField(upload_to='past papers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg'])]),
        ),
    ]
