# Generated by Django 5.0.3 on 2024-05-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0016_order_pending_status_order_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='provider',
            field=models.CharField(choices=[('Tigo', 'Tigo'), ('Mpesa', 'Mpesa'), ('Airtel', 'Airtel'), ('Halopesa', 'Halopesa'), ('Azampesa', 'Azampesa')], max_length=50),
        ),
    ]
