# Generated by Django 5.0.6 on 2024-05-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0021_rename_subscription_user_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')], default=0),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
