# Generated by Django 5.0.6 on 2024-06-07 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0022_alter_user_year_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
