# Generated by Django 5.0.3 on 2024-04-04 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0010_user_degree_program_user_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='year',
        ),
    ]
