# Generated by Django 5.0.3 on 2024-04-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0011_remove_user_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='degree_program',
        ),
    ]
