# Generated by Django 5.0.3 on 2024-04-12 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_system', '0012_delete_userprofile'),
        ('myusers', '0012_remove_user_degree_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='degree_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_system.degreeprogram'),
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')], default=1),
            preserve_default=False,
        ),
    ]
