# Generated by Django 5.0.3 on 2024-05-02 14:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0013_user_degree_program_user_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ordertoken', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
