# Generated by Django 5.0.3 on 2024-05-05 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0017_alter_order_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pending_status',
        ),
    ]
