insert into learning_system_course (id, name, description, notes, semester, year, degree_id) values
('CL111-CEIT', 'Communication skills for engineers', 'https://drive.google.com/drive/folders/1KLK2QevBZeEGxobK9itXol7gL_U-uP6f', 'CL111', 1, 1, 'CEIT'),
('CS151-CS', 'Computer organization and architecture 1', 'https://drive.google.com/drive/folders/1RALo95bqm07KxG2BOG4ln5EeEsuhdyQK', 'CS151', 1, 1, 'CS'),
('CS173-CS', 'Business computer communication', 'https://drive.google.com/drive/folders/1xOfEESqvKuPNOBQMgHcKkP-Pmerv_EDT', 'CS173', 2, 1, 'CS'),
('CS174-CS', 'Programming in C', 'https://drive.google.com/drive/folders/1eCq-yx3cwBmbEk1Gje7nBVqpkSnD_DEN', 'CS174', 1, 1, 'CS'),
('CS175-CS', 'Programming in Java', 'https://drive.google.com/drive/folders/1_zi_W-3VNVvZCl_9i7NUeXJdN5k3VJu3', 'CS175', 2, 1, 'CS'),
('CS211', 'Characteristics of Instruments & Measurement Systems', 'https://drive.google.com/drive/folders/1TB1rEN4m3-Jggzq_ooZV2YCWfNe3PhCc', 'CS211', 1, 2, 'CEIT'),
('CS243-CS', 'Computer Network Design and Administration', 'https://drive.google.com/drive/folders/19Qfm1v_JCUj0qL9wU3kKYPpv5bYJ1jvx', 'CS243', 1, 2, 'CS'),
('CS252-CS', 'Computer Organization and Architecture 2', 'https://drive.google.com/drive/folders/1JSKm7F9tvt1QQeEpZtl9rZBKXxCwlO3P', 'CS252', 2, 2, 'CS'),
('DS112-CS', 'Development perspective 1', 'https://drive.google.com/drive/folders/19NAZRr3y9xb91mw7k0YB7pWCHwcS4LrY', 'DS112', 1, 1, 'CS'),
('DS113-CS', 'Development perspective 2', 'https://drive.google.com/drive/folders/1aYZqzeGKTbeHSaGyjXCllbrT6vFwPnIl', 'DS113', 2, 1, 'CS'),
('ES110', 'Analogue Electronics', 'https://drive.google.com/drive/folders/1bB98MyFvTtfoHUrxEc8-mnrDzElsq3i1', 'ES110', 2, 1, 'CEIT'),
('ES120', 'Introduction to CAD', 'https://drive.google.com/drive/folders/15y1TnKhvEiYgro2GSbYqEvHMP0cBslOr', 'ES120', 2, 1, 'CEIT'),
('ES171', 'Computer Aided Drafting and Design (CADD)', 'https://drive.google.com/drive/folders/1P5r9b9cwf7oCmBBqCqxWKZwH1Xqj1RV8', 'ES171', 2, 1, 'CEIT'),
('ES211', 'Analogue Electronics 2', 'https://drive.google.com/drive/folders/1DUC-7wzn-sfcVnBhlEZwB_8B5pupHQMG', 'ES211', 1, 2, 'CEIT'),
('IS143', 'Discrete structures', 'https://drive.google.com/drive/folders/1GX-Z4OVLE5wlK2spDEc9tZv-uhH1yqh-', 'IS143', 2, 1, 'CS'),
('ME101', 'Engineering Drawing', 'https://drive.google.com/drive/folders/1Bx06rz62jhek8qUnqO7sVQAEjWXODGjN', 'ME101', 1, 1, 'CEIT'),
('MT161', 'Matrices and basic calculus for non-majors', 'https://drive.google.com/drive/folders/1rEzRJRaLKFV0XHP7SidLEFadWJGxqUGD', 'MT161', 1, 1, 'CEIT'),
('MT171', 'One variable calculus and differential equations for non-majors', 'https://drive.google.com/drive/folders/1qw9dOgomeTaldzVsl2PWkbgtcoMsUvfD', 'MT171', 2, 1, 'CEIT'),
('MT261', 'Several Variable Calculus', 'https://drive.google.com/drive/folders/1rU7C81j4U02j2YGQONKMUo-74g1_YW2Z', 'MT261', 1, 2, 'CEIT'),
('IS158-CS', 'Computer hardware and System maintenance', 'https://drive.google.com/drive/folders/1mv4iDxnljnHaHuAlRCyf4dHtMIF4t5os', 'IS158', 2, 1, 'CS'),
('CS234-CS', 'Object Oriented Programming in Java', 'https://drive.google.com/drive/folders/1U-9JooDLH9Y5rmYDJqE4I4ImX-JDpaJX', 'CS234', 2, 2, 'CS'),
('IS158-CEIT', 'Computer Hardware and Maintanence', 'https://drive.google.com/drive/folders/1IyG5A0BmpAw8-1Q81drQBaxAeADlVrlk', 'IS158', 2, 1, 'CEIT'),
('MT249', 'Mathematical Logic and Formal Semantics', 'https://drive.google.com/drive/folders/1jnHH5EzRjylxQq_VnKMmXQwndBB2vYd9', 'MT249', 2, 2, 'CS'),
('IS162-CS', 'Introduction to information system', 'https://drive.google.com/drive/folders/1839Ry8kQNJYfsNMht8hRyRObxwMfsnJU', 'IS162', 1, 1, 'CS'),
('IS171-CS', 'Introduction to computer networks', 'https://drive.google.com/drive/folders/1Howi-q1Qzkjm8c1SjKOQHI3IcA4N6au9', 'IS171', 2, 1, 'CS'),
('IS181', 'Web Programming', 'https://drive.google.com/drive/folders/1pr1VDYCTAwxE4PZVUIZ4Hyxt4Hp7kcYi', 'IS181', 2, 1, 'CS'),
('IS236-CS', 'Structured System Analysis and Design', 'https://drive.google.com/drive/folders/1vwO9pFaOv9U3rZ6nYLzl_28rN4XufG6x', 'IS236', 1, 2, 'CS'),
('IS237', 'Data Abstraction and Algorithm', 'https://drive.google.com/drive/folders/1QZvs5PoV4lQz4iGciIS4mXtWL1pMl21E', 'IS237', 1, 2, 'CS'),
('IS238', 'Mobile Application Development', 'https://drive.google.com/drive/folders/1QyWcVN0JBiWNbPTT55M5Zpd7Cud0qoxN', 'IS238', 1, 2, 'CS'),
('IS239', 'Algorithms and Complexity', 'https://drive.google.com/drive/folders/1FxUdtIdOLTeh9GyW-erZDhBFm4PGeIuO', 'IS239', 2, 2, 'CS'),
('IS246', 'Principles of Computer Graphics', 'https://drive.google.com/drive/folders/1GGAd_iHTDDuu2F_VjQ1nhNb9AECC7TXO', 'IS246', 1, 2, 'CS'),
('IS264', 'Principles of Database systems', 'https://drive.google.com/drive/folders/1XWYauDawYAYG0z6IOwo7-a7IHI3Ddyi-', 'IS264', 1, 2, 'CS'),
('IS274-CS', 'Object Oriented Analysis and Design', 'https://drive.google.com/drive/folders/1a4FdFjVQBby77KL4zJ01wUzvI1F7MsVv', 'IS274', 2, 2, 'CS'),
('IS283', 'Web Services and Technologies', 'https://drive.google.com/drive/folders/16s-R1VTsoDCeXGGmCUIqPRMqn31CCY3R', 'IS283', 2, 2, 'CS'),
('MT100', 'Foundation of analysis', 'https://drive.google.com/drive/folders/1AaawOS6dIPKl2o3k4-BCliRLdrHSYJy_', 'MT100', 1, 1, 'CS'),
('MT278', 'Linear Programming', 'https://drive.google.com/drive/folders/1I7dxbTitHLM9wUFcHqcSjaAw1lRx87Eu', 'MT278', 2, 2, 'CS'),
('TE172', 'Computer Hardware workshop', 'https://drive.google.com/drive/folders/1Z0hiiNFT41GJBtjvLrdMdWx79Re1BeVT', 'TE172', 1, 1, 'CEIT'),
('CL111-CS', 'Communication skills for engineers', 'https://drive.google.com/drive/folders/1HuPD4efRKeG6f2I6e3XXU_wKwyB8g-fp', 'CL111', 1, 1, 'CS'),
('CS151-CEIT', 'Computer organization and architecture 1', 'https://drive.google.com/drive/folders/1T038b-GtlbHScaQdPBLFb0YfxNbEZ6hd', 'CS151', 1, 2, 'CEIT'),
('CS173-CEIT', 'Business computer communication', 'https://drive.google.com/drive/folders/1qVvIf8a6N6fCBtZx6akp5saEewTDkhHm', 'CS173', 2, 1, 'CEIT'),
('CS174-CEIT', 'Programming in C', 'https://drive.google.com/drive/folders/1kjkeH9wogmbkdAMVlkEKy8TvkAR4p5-h', 'CS174', 1, 1, 'CEIT'),
('CS175-CEIT', 'Programming in Java', 'https://drive.google.com/drive/folders/15Yuiq9FducvF3Is2wBJb-43I3BYcnVFR', 'CS175', 2, 1, 'CEIT'),
('DS113-CEIT', 'Development perspective', 'https://drive.google.com/drive/folders/1MlU6nVL0xLAicJDCf2tmhqslub0j4oBR', 'DS112', 2, 1, 'CEIT'),
('IS265', 'Introduction to GIS', 'https://drive.google.com/drive/folders/1RhV0hu6tDBHrjJ9cmMOLpPs1F6_Ku5xm', 'IS265', 1, 2, 'CS'),
('DS112-CEIT', 'Development perspective 1', 'https://drive.google.com/drive/folders/1PmFDobbGsPzXzcHXGvMJ_q1dvNw3Expr', 'DS112', 1, 1, 'CEIT'),
('CS252-CEIT', 'Computer Organization and Architecture 2', 'https://drive.google.com/drive/folders/1wV9zuUw0kU_WssfX-WxuWIegGzlO6uDV', 'CS252', 2, 2, 'CEIT'),
('CS243-CEIT', 'Computer Network Design and Administration', 'https://drive.google.com/drive/folders/1X_rKZVr-QjFeJS6vnT9H7muaIRznysWc', 'CS243', 1, 2, 'CEIT'),
('IS171-CEIT', 'Introduction to computer networks', 'https://drive.google.com/drive/folders/1axr73awvuXjuZjBsi3p8vVg9IvjSNBl1', 'IS171', 2, 1, 'CEIT'),
('IS274-CEIT', 'Object Oriented Analysis and Design', 'https://drive.google.com/drive/folders/1a4FdFjVQBby77KL4zJ01wUzvI1F7MsVv', 'IS274', 2, 2, 'CEIT'),
('CS212', 'Measurement & Instrumentation Engineering 2', 'https://drive.google.com/drive/folders/1EFmujiS7q02_8zukQIC5fHNp4CcSuhMF', 'CS212', 2, 2, 'CEIT'),
('ES221', 'Digital Electronics 2', 'https://drive.google.com/drive/folders/1BTAumnuabsuH0IzVDSnqDN0XWxaGqlgi', 'ES221', 2, 2, 'CEIT'),
('TE231', 'Fundamentals of signals and systems', 'https://drive.google.com/drive/folders/1lCiRoN1Zg9AFMcSuaGrK_xQ218vAXQ3X', 'TE231', 2, 2, 'CEIT'),
('IS236-CEIT', 'Structured System Analysis and Design', 'https://drive.google.com/drive/folders/1tCjv9jK-rn_hoYHbAFBFkHNnWqfygan2', 'IS236', 1, 2, 'CEIT'),
('CS234-CEIT', 'Object Oriented Programming in Java', 'https://drive.google.com/drive/folders/12xsYAbybFNcE_blgScoQLbM-6ljn1FVd', 'CS234', 2, 2, 'CEIT');
